# Generated by Django 4.2.15 on 2025-05-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="means_of_identification",
            field=models.CharField(
                choices=[
                    ("drivers_license", "Drivers License"),
                    ("national_id", "National ID"),
                    ("passport", "Passport"),
                ],
                default="drivers_license",
                max_length=20,
                verbose_name="Means of Identification",
            ),
        ),
    ]
