# Generated by Django 4.2.15 on 2025-06-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_profile_means_of_identification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("us_dollar", "Dollar"),
                    ("pound_sterling", "Pound Sterling"),
                    ("indian_rupees", "Indian Rupees"),
                ],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("savings", "Savings")],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
    ]
